# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.600    # 1600mm/s
  max_trans_acc: 1.000    # 1000mm/s2
  max_trans_dec: -1.000   # -1000mm/s2
  max_rot_vel: 0.78       # pi/4 rad/s ( 90deg/s)
