# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 0.400    # 400mm/s
  max_trans_acc: 0.800    # 800mm/s2
  max_trans_dec: -0.800   # -800mm/s2
  max_rot_vel: 0.78       # pi/4 rad/s ( 90deg/s)
